INSERT INTO accessory_catalog(category, model, name, geometry_json, mount_rule_json, bom_rule_json, enabled)
VALUES
('END_CAP', '3030-END', '3030 黑色端盖',
 '{"size":30,"thickness":6,"material":"尼龙"}',
 '{"target":"PROFILE_END","profileNominal":"3030"}',
 '{"unit":"个","material":"尼龙"}', 1),
('END_CAP', '4040-END', '4040 黑色端盖',
 '{"size":40,"thickness":7,"material":"尼龙"}',
 '{"target":"PROFILE_END","profileNominal":"4040"}',
 '{"unit":"个","material":"尼龙"}', 1),
('END_CAP', '6060-END', '6060 黑色端盖',
 '{"size":60,"thickness":8,"material":"尼龙"}',
 '{"target":"PROFILE_END","profileNominal":"6060"}',
 '{"unit":"个","material":"尼龙"}', 1),
('FOOT', 'M8-40', 'M8 调节脚杯 Ø40',
 '{"stemDiameter":8,"stemLength":45,"footDiameter":40,"footThickness":8,"thread":"M8","material":"镀锌钢+尼龙"}',
 '{"target":"PROFILE_END","thread":"M8"}',
 '{"unit":"个","material":"镀锌钢+尼龙"}', 1),
('FOOT', 'M10-50', 'M10 调节脚杯 Ø50',
 '{"stemDiameter":10,"stemLength":55,"footDiameter":50,"footThickness":10,"thread":"M10","material":"镀锌钢+尼龙"}',
 '{"target":"PROFILE_END","thread":"M10"}',
 '{"unit":"个","material":"镀锌钢+尼龙"}', 1),
('FOOT', 'M12-60', 'M12 调节脚杯 Ø60',
 '{"stemDiameter":12,"stemLength":70,"footDiameter":60,"footThickness":12,"thread":"M12","material":"镀锌钢+尼龙"}',
 '{"target":"PROFILE_END","thread":"M12"}',
 '{"unit":"个","material":"镀锌钢+尼龙"}', 1),
('CASTER', 'FUMA60', '福马轮 60',
 '{"wheelDiameter":60,"wheelWidth":25,"stemDiameter":10,"stemLength":25,"brake":true,"material":"钢+PU"}',
 '{"target":"PROFILE_BOTTOM","mount":"STEM"}',
 '{"unit":"个","material":"钢+PU"}', 1),
('CASTER', 'FUMA75', '福马轮 75',
 '{"wheelDiameter":75,"wheelWidth":30,"stemDiameter":12,"stemLength":30,"brake":true,"material":"钢+PU"}',
 '{"target":"PROFILE_BOTTOM","mount":"STEM"}',
 '{"unit":"个","material":"钢+PU"}', 1),
('DRAWER_SLIDE', 'SLIDE-450-3S', '450 mm 三节抽屉滑轨',
 '{"length":450,"width":12,"height":45,"material":"冷轧钢"}',
 '{"target":"PANEL_SIDE","side":"BOTH"}',
 '{"unit":"副","material":"冷轧钢"}', 1),
('DRAWER_SLIDE', 'SLIDE-500-3S', '500 mm 三节抽屉滑轨',
 '{"length":500,"width":12,"height":45,"material":"冷轧钢"}',
 '{"target":"PANEL_SIDE","side":"BOTH"}',
 '{"unit":"副","material":"冷轧钢"}', 1)
ON CONFLICT(model) DO UPDATE SET
    category = excluded.category,
    name = excluded.name,
    geometry_json = excluded.geometry_json,
    mount_rule_json = excluded.mount_rule_json,
    bom_rule_json = excluded.bom_rule_json,
    enabled = excluded.enabled,
    updated_at = CURRENT_TIMESTAMP;
